name: Tazle
favicon: null
layout_spectrum: 0.9464805964380503
typography_spectrum: 0.03732198942452669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9882296901196241
  lightness: 0.7583805669564754
  saturation: 0.09982590610161424
  rhythmicContrast: 0.27711128583177924
purpose: []
